server:
  # 端口
  port: 8060

#spring
spring:
  datasource:
    name: activiti
    # useAffectedRows，sql执行后返回受影响的行数
    url: jdbc:mysql://127.0.0.1:3306/${spring.datasource.name}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    static-path-pattern: /**
    resources:
      static-locations: classpath:/templates/,classpath:/static/,classpath:/public/

  thymeleaf:
    cache: false
    mode: LEGACYHTML5


security:
  basic:
    enabled: false

